### PR TITLE
Refresh to 1.9 official tag

### PR DESCRIPTION
**Pull request by npanpaliya**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Updates to DALI 1.10. https://github.com/open-ce/open-ce/issues/570

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by cdeepali — APPROVED** [review]

**Comment by alexlang74** [comment]
Why did you update to a `-dev` version ?  I didn't see any info that `1.10` is about to get released...

**Comment by npanpaliya** [comment]
Even in 1.5.0, we had updated DALI recipe to build 1.9.0-dev tag as 1.9.0 was not tagged. NVIDIA usually creates tags for <version>-dev too.

**Comment by alexlang74** [comment]
Ah, thanks for clarifying, @npanpaliya !

**Review by alexlang74 — APPROVED** [review]

**Comment by JanuszL** [comment]
Hi @alexlang74 and @npanpaliya,

1.9 has not been released yet. It is expected this/next week.

**Comment by npanpaliya** [comment]
@JanuszL - Thanks for the information.

Do you think we should not use -dev tags?

**Comment by JanuszL** [comment]
Hi @alexlang74 and @npanpaliya,

1.9 has not been released yet. It is@npanpaliya,

I think it is safer not to use it for official releases. -dev tag is the beginning of the development of the next DALI version. The tag without -dev can include additional bug fixes for problems found during the QA cycle. You can compare [1.10-dev](https://github.com/NVIDIA/DALI/commits/v1.10.0-dev) with [1.9 release branch](https://github.com/NVIDIA/DALI/commits/release_v1.9). expected this/next week.

**Comment by JanuszL** [comment]
@npanpaliya,

1.9 is out - https://github.com/NVIDIA/DALI/releases/tag/v1.9.0.

**Comment by npanpaliya** [comment]
> @npanpaliya,
> 
> 1.9 is out - https://github.com/NVIDIA/DALI/releases/tag/v1.9.0.

Wow! This is super fast! Thanks @JanuszL

**Review by alexlang74 — APPROVED** [review]

**Review by cdeepali — APPROVED** [review]

**Pull request merged**
